spring.application.name=task-management-app

spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=app
spring.datasource.password=app
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
